services:
  qrky:
    build:
      context: .
      dockerfile: Dockerfile
    image: qrky:latest
    container_name: qrky
    environment:
      - QRKY_DEFAULT_URL=http://localhost:8501
    ports:
      - "8501:8501"
